# Generated by Django 4.0.6 on 2022-10-10 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_id', models.PositiveIntegerField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=355, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, max_length=355, null=True)),
                ('description', models.TextField(blank=True, max_length=355, null=True)),
                ('creation_datetime', models.DateTimeField(blank=True, null=True)),
                ('requester', models.CharField(blank=True, max_length=255, null=True)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('submitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, max_length=355, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
        ),
    ]
